### PR TITLE
Number pattern programs

### PR DESCRIPTION
**Pull request by Baba-Yaga-1**
I have added three programs - left triangle, right triangle and pyramid.
#32 
Can you check the PR?

### CODE REVIEW

**Comment by fms12** [comment]
@Baba-Yaga-1  can you please change the name "serial no" to its pattern number? you can check it out in the pattern folder in the repo as reference

**Comment by fms12** [comment]
> @Baba-Yaga-1 can you please change the name because it is not "serial no" its a pattern number. you can check it out in the pattern folder in the repo as a reference

**Comment by Baba-Yaga-1** [comment]
I have made the necessary changes and have also pushed it.

**Comment by Baba-Yaga-1** [comment]
> > @Baba-Yaga-1 can you please change the name because it is not "serial no" its a pattern number. you can check it out in the pattern folder in the repo as a reference

I have made the necessary changes.

**Comment by fms12** [comment]
@Baba-Yaga-1  thank you for your contribution please do like the repo

**Pull request merged**
