### PR TITLE
cleaned files to follow flake8 coding style guide

### PR DESCRIPTION
**Pull request by devvspaces**
Resolved issue #141 

 - [x] Made sure all file names don't have spaces in them
 - [x] Cleaned files to follow consistent style guide
 - [x] Tests can now pass flake8 tests
 - [x] Enforced that all new PR must follow style guidelines

### CODE REVIEW

**Review by fms12 — APPROVED** [review]

**Comment by fms12** [comment]
if you are able to resolve the deep source issue it will be better.

**Comment by devvspaces** [comment]
Okay i am working on it

**Comment by devvspaces** [comment]
where is the gitpod, or do you mean git action. I don't know gitpod

**Comment by fms12** [comment]
> where is the gitpod, or do you mean git action. I don't know gitpod

go to the readme of this repo. there you find it

**Comment by devvspaces** [comment]
okay

**Comment by devvspaces** [comment]
Hi, I am checking out the gitpod, I have completed the deepsource issue. It should all be good from now on, I will try to write tests for other algorithms that does not have tests. Thanks @fms12

**Review by fms12 — APPROVED** [review]

**Pull request merged**
