### PR TITLE
Implemented Binary Search Tree with Python

### PR DESCRIPTION
**Pull request by Kd-Here**
Hello geek 
Implemented BST with Python.
Let me know if you have a doubt!

### CODE REVIEW

**Comment by Kd-Here** [comment]
@fms12 please review and let me know if you have other similar tasks.

**Comment by fms12** [comment]
pass these checks

**Comment by fms12** [comment]
For example, So your directory structure could be like this;

```
- DATA-STRUCTURE-AND-ALGORITHM-IN-PY
   -  LinkedList
       - Doubly
       - Singly
       - ReversedSingly     <----------- This will be your newly created folder
           - solution.py       <----------- Write the code for the implementation here
           - test_solution.py <----------- Write a test for it here to make sure it's working
```

There is already a LinkedList directory, which includes full Doubly and Singly linked list implementation. You can add yours Has a new directory ReversedSingly, then write the solution and test for it there.

Anyone could also add tests for it in the future to learn it.

**Comment by Kd-Here** [comment]
Hey @fms12 can you guide me.
I want to know how to successfully passed the pytest run by github!

**Comment by fms12** [comment]
click s

> Hey @fms12 can you guide me. I want to know how to successfully passed the pytest run by github!

go and click on the details of every pytest. 
image
then you will get the error.

**Comment by Kd-Here** [comment]
Thanks for helping me with that.
I check but there are also errors in different file!
image
image
**I resolved error from my file!**

**Comment by fms12** [comment]
@devvspaces  can you look at this?

**Comment by Kd-Here** [comment]
Please help me in that!
I give a lot of try. Still can't figure out where gone wrong.

**Comment by devvspaces** [comment]
> @devvspaces  can you look at this?

Sure I wil

**Comment by Kd-Here** [comment]
@devvspaces @fms12 I found the reason for failure.
It's bcoz of others file which get merged in main before setting the automated pytest.
<https://pybit.es/articles/linting-with-flake8/>
Now we have 2 options we can ignore those error by a ignore script. (I can do this )
Or we can make change in each file.

Let me know what to do.

**Comment by devvspaces** [comment]
I will let me check it

**Comment by Kd-Here** [comment]
Hope this time Mayank it will get merge.
I tried each file having error. Can you please run the test.

**Comment by fms12** [comment]
> Hope this time Mayank it will get merge. I tried each file having error. Can you please run the test.


@Kd-Here  you have to add comments in the binary search code .

**Comment by Kd-Here** [comment]
> > Hope this time Mayank it will get merge. I tried each file having error. Can you please run the test.
> 
> @Kd-Here you have to add comments in the binary search code .

In file binary_search.py?
I think we need to change testing part. Because testing part was added after many PR. Which giving error in latest PR.
`Can you merge  my PR`. I will try to edit all code later with automated tool.

**Comment by fms12** [comment]
> > > Hope this time Mayank it will get merge. I tried each file having error. Can you please run the test.
> > 
> > 
> > @Kd-Here you have to add comments in the binary search code .
> 
> In file binary_search.py? I think we need to change testing part. Because testing part was added after many PR. Which giving error in latest PR. `Can you merge my PR`. I will try to edit all code later with automated tool.

all things are good just add comment in your code "Binary search  tree code "

**Comment by devvspaces** [comment]
Hi, i am on this now

**Comment by devvspaces** [comment]
@Kd-Here , this was the first error you got in your PR, it's just a deep source python error. This is the first commit https://github.com/fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY/pull/216/commits/4d81a910fcacb5ada7512566cd6db671cdadc6cc

When you started having flake8 problems was here https://github.com/fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY/pull/216/commits/9e547ad4ca6a8db165bf921fcb7c92bde18e6a20.

**Comment by devvspaces** [comment]
I see you have edited others code too, what you can do now, to not worry yourself is this.
1. Copy the folder that contains just your code. Place is somewhere else, outside of your repo.
2. Create another repo using fork
3. Place your folder back to it's position and make a PR, let's start from there.

Reason is this, when i run flake8 now on the current code base there were zero errors. Now i see you have edited a lot of other files, that are now showing error with flake8

**Comment by devvspaces** [comment]
Do you understand me @Kd-Here

**Comment by Kd-Here** [comment]
Yes I got it.
I will create a PR of only changes in my code.

**Pull request closed without merging**
