### PR TITLE
Update in trail1

### PR DESCRIPTION
**Pull request by Kd-Here**
Can we make a trail here with this PR.

### CODE REVIEW

**Comment by Kd-Here** [comment]
@devvspaces 
@fms12 
This is new branch were I am making changes for BST please check it!

**Comment by devvspaces** [comment]
Okay let me check it now, give me 5 mins

**Comment by devvspaces** [comment]
Okay i will work on these ones now

**Comment by devvspaces** [comment]
so i have updated the actual repo codes now, check this PR #218 
You should just add your tests now, and push. Then tag me, i would come and merge it. Thanks @Kd-Here

**Comment by Kd-Here** [comment]
@devvspaces Have a look at latest commit added some test cases.
Please make a actions run on it.

**Comment by fms12** [comment]
@Kd-Here  check the test now there are issues in your file.

**Comment by fms12** [comment]
Thank you for your contribution.

**Comment by Kd-Here** [comment]
Can I contribute more here.
On other algo?

**Comment by fms12** [comment]
yaa sure .

**Pull request merged**
